name: Check go mod tidy

on: [push]

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code
